name: Sync and Merge Upstream Repositories
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  sync-and-merge:
    runs-on: ubuntu-latest
    env:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      TARGET_REPO: t96mytell/openwrt-packages-23.05
      TARGET_BRANCH: main
    
    steps:
      # Step 0: Checkout Target Repository
      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TARGET_REPO }}
          ref: ${{ env.TARGET_BRANCH }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
      
      # 确保初始提交存在
      - name: Ensure initial commit exists
        run: |
          if git rev-parse --verify HEAD >/dev/null 2>&1; then
            echo "仓库已有提交记录"
          else
            echo "创建初始提交..."
            touch README.md
            git add README.md
            git commit -m "Initial commit"
            git push origin ${{ env.TARGET_BRANCH }}
          fi
      
      # Step 1: 改进的同步逻辑 - 确保上游更新被应用
      - name: Smart Sync with Upstream Updates
        run: |
          set -euo pipefail
          
          # 配置Git用户
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # 主同步函数 - 确保上游更新被应用
          smart_sync() {
            local repo_url=$1
            local branch=$2
            local remote_name=$3
            local mapping=$4
            local excludes=${5:-}
            
            echo "========================================"
            echo "处理仓库: $repo_url (分支: $branch)"
            echo "远程名称: $remote_name"
            echo "映射关系: $mapping"
            echo "排除规则: ${excludes:-无}"
            echo "----------------------------------------"
            
            # 添加上游远程仓库
            git remote add "$remote_name" "https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@$repo_url"
            git fetch "$remote_name" "$branch" --depth=1
            
            # 创建临时合并分支
            local temp_branch="merge-${remote_name}"
            git checkout -b "$temp_branch"
            
            # 创建临时克隆目录
            local clone_dir="temp_${remote_name}_clone"
            git clone --quiet --depth 1 --branch "$branch" \
              "https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@$repo_url" \
              "$clone_dir"
            
            # 构建rsync排除参数
            local rsync_excludes=()
            if [ -n "$excludes" ]; then
              IFS=',' read -ra exclude_list <<< "$excludes"
              for pattern in "${exclude_list[@]}"; do
                rsync_excludes+=(--exclude="$pattern")
              done
            fi
            
            # 默认排除.git和.gitignore
            rsync_excludes+=(--exclude='.git' --exclude='.gitignore')
            
            echo "使用排除规则: ${rsync_excludes[*]}"
            
            # 解析映射关系
            IFS=',' read -ra mappings <<< "$mapping"
            for map in "${mappings[@]}"; do
              # 去除空格
              map=$(echo "$map" | tr -d '[:space:]')
              IFS=':' read -r src_path dest_path <<< "$map"
              
              # 特殊处理根目录映射
              if [ -z "$src_path" ]; then
                src_path="."
              fi
              
              # 完整的源路径
              local full_src="$clone_dir/$src_path"
              
              # 检查源路径是否存在
              if [ ! -e "$full_src" ]; then
                echo "警告: 源路径 '$full_src' 不存在，跳过"
                continue
              fi
              
              echo "同步: $src_path → $dest_path"
              
              # 确保目标目录存在
              mkdir -p "$(dirname "$dest_path")"
              
              # 使用rsync进行同步 - 关键修复: 使用--update参数
              # 只更新比目标文件新的文件或目标不存在的文件
              if [ -d "$full_src" ]; then
                # 同步目录 - 使用--update保留目标仓库的修改
                rsync -rlptD --update "${rsync_excludes[@]}" "$full_src/" "$dest_path/"
              else
                # 同步文件
                rsync -rlptD --update "${rsync_excludes[@]}" "$full_src" "$dest_path"
              fi
              
              # 添加详细的同步报告
              echo "同步完成 - 详细变更:"
              rsync -rlptDn --update "${rsync_excludes[@]}" "$full_src/" "$dest_path/" | grep -v '^$' || true
            done
            
            # 清理临时克隆目录
            rm -rf "$clone_dir"
            
            # 提交上游更改
            git add .
            if ! git diff-index --quiet HEAD; then
              git commit -m "Sync from ${remote_name} ${branch}"
              echo "已提交上游更新"
            else
              echo "没有需要提交的上游更新。"
            fi
            
            # 合并回主分支 - 使用ours策略保留目标仓库更改
            git checkout ${{ env.TARGET_BRANCH }}
            
            # 添加详细的合并前差异报告
            echo "合并前差异报告:"
            git diff HEAD "$temp_branch" --name-status || true
            
            # 执行合并 - 关键修复: 使用--no-ff确保创建合并提交
            git merge "$temp_branch" -m "Merge updates from ${remote_name}" -X ours --no-ff
            
            # 添加详细的合并后状态
            echo "合并后状态:"
            git status -s
            
            # 清理
            git branch -D "$temp_branch"
            git remote remove "$remote_name"
            
            echo "----------------------------------------"
            echo "仓库处理完成: $repo_url"
            echo "========================================"
          }
          
          # 同步Siriling/5G-Modem-Support
          smart_sync "github.com/Siriling/5G-Modem-Support.git" "main" "5G-Modem-Support" \
            "fibocom-dial:fibocom-dial,\
            fibocom_MHI:fibocom_MHI,\
            fibocom_QMI_WWAN:fibocom_QMI_WWAN,\
            luci-app-cpe:luci-app-cpe,\
            luci-app-gobinetmodem:luci-app-gobinetmodem,\
            luci-app-hypermodem:luci-app-hypermodem,\
            luci-app-modem:luci-app-modem,\
            luci-app-pcimodem:luci-app-pcimodem,\
            luci-app-sms-tool:luci-app-sms-tool,\
            luci-app-spdmodem:luci-app-spdmodem,\
            luci-app-usbmodem:luci-app-usbmodem,\
            meig-cm:meig-cm,\
            meig_QMI_WWAN:meig_QMI_WWAN,\
            quectel_Gobinet:quectel_Gobinet,\
            quectel_MHI:quectel_MHI,\
            quectel_QMI_WWAN:quectel_QMI_WWAN,\
            quectel_SRPD_PCIE:quectel_SRPD_PCIE,\
            quectel_cm_5G:quectel_cm_5G,\
            sendat:sendat,\
            sms-tool:sms-tool"
          
          # 同步immortalwrt/packages
          smart_sync "github.com/immortalwrt/packages.git" "master" "immortalwrt-packages" \
            "lang/lua-neturl:lua-neturl,\
            net/keepalived:keepalived"

          # 同步immortalwrt/luci
          smart_sync "github.com/immortalwrt/luci.git" "master" "immortalwrt-luci" \
            "applications/luci-app-keepalived:luci-app-keepalived"
          
          # 同步kenzok8/small-package
          smart_sync "github.com/kenzok8/small-package.git" "main" "small-package" \
            "luci-app-adguardhome:luci-app-adguardhome,\
            adguardhome:adguardhome"

          # 同步kenzok8/small
          smart_sync "github.com/kenzok8/small.git" "master" "small" \
            "brook:brook,\
            chinadns-ng:chinadns-ng,\
            dns2socks:dns2socks,\
            dns2tcp:dns2tcp,\
            gn:gn,\
            hysteria:hysteria,\
            ipt2socks:ipt2socks,\
            luci-app-bypass:luci-app-bypass,\
            luci-app-fchomo:luci-app-fchomo,\
            luci-app-homeproxy:luci-app-homeproxy,\
            luci-app-mosdns:luci-app-mosdns,\
            luci-app-nikki:luci-app-nikki,\
            luci-app-openclash:luci-app-openclash,\
            luci-app-passwall:luci-app-passwall,\
            luci-app-passwall2:luci-app-passwall2,\
            luci-app-ssr-plus:luci-app-ssr-plus,\
            microsocks:microsocks,\
            mihomo:mihomo,\
            mosdns:mosdns,\
            naiveproxy:naiveproxy,\
            nikki:nikki,\
            pdnsd-alt:pdnsd-alt,\
            redsocks2:redsocks2,\
            shadow-tls:shadow-tls,\
            shadowsocks-rust:shadowsocks-rust,\
            shadowsocksr-libev:shadowsocksr-libev,\
            simple-obfs:simple-obfs,\
            sing-box:sing-box,\
            ssocks:ssocks,\
            tcping:tcping,\
            trojan-go:trojan-go,\
            trojan-plus:trojan-plus,\
            trojan:trojan,\
            tuic-client:tuic-client,\
            v2dat:v2dat,\
            v2ray-core:v2ray-core,\
            v2ray-geodata:v2ray-geodata,\
            v2ray-geoview:v2ray-geoview,\
            v2ray-plugin:v2ray-plugin,\
            v2raya:v2raya,\
            xray-core:xray-core,\
            xray-plugin:xray-plugin"

          # 同步kiddin9/kwrt-packages
          smart_sync "github.com/kiddin9/kwrt-packages.git" "main" "kwrt-packages" \
            "luci-app-easymesh:luci-app-easymesh,\
            luci-app-leigod-acc:luci-app-leigod-acc,\
            leigod-acc:leigod-acc,\
            luci-app-uugamebooster:luci-app-uugamebooster,\
            uugamebooster:uugamebooster,\
            shadowsocks-libev:shadowsocks-libev,\
            fullconenat-nft:fullconenat-nft,\
            luci-app-dockerman:luci-app-dockerman,\
            dockerd:dockerd,\
            luci-app-pptp-server:luci-app-pptp-server,\
            luci-app-pppoe-relay:luci-app-pppoe-relay,\
            luci-app-pppoe-server:luci-app-pppoe-server,\
            luci-app-openvpn-server:luci-app-openvpn-server,\
            luci-app-openvpn-client:luci-app-openvpn-client,\
            luci-app-ipsec-server:luci-app-ipsec-server,\
            luci-app-ipsec-vpnd:luci-app-ipsec-vpnd,\
            luci-app-zerotier:luci-app-zerotier,\
            luci-app-einat:luci-app-einat,\
            openwrt-einat-ebpf:openwrt-einat-ebpf,\
            dns2socks-rust:dns2socks-rust"
          
          echo "========================================"
          echo "所有仓库同步完成!"
          echo "========================================"
      
      # Step 2: 推送更改
      - name: Push Changes
        run: |
          git remote set-url origin "https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ env.TARGET_REPO }}.git"
          
          # 检查是否有未提交的更改
          if git diff-index --quiet HEAD; then
            echo "没有需要提交的更改"
          else
            # 添加所有更改
            git add .
            # 提交更改
            git commit -m "自动同步: 从上游仓库更新 $(date +'%Y-%m-%d %H:%M:%S')"
          fi
          
          # 尝试推送
          echo "尝试推送更改到远程仓库..."
          if ! git push origin ${{ env.TARGET_BRANCH }}; then
            echo "推送失败，可能存在冲突或过时的本地分支"
            echo "执行拉取并变基..."
            git pull origin ${{ env.TARGET_BRANCH }} --rebase --autostash
            echo "重新尝试推送..."
            git push origin ${{ env.TARGET_BRANCH }}
          fi
          echo "更改已成功推送!"
      
      # Step 3: 清理工作流运行记录
      - name: Cleanup old workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 7
          keep_minimum_runs: 5
          repository: ${{ github.repository }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
